// Build the LOOM sidecar into a single self-contained ESM file with no `tsx`
// runtime, no repo-relative paths, and no node_modules required at run time —
// the form the loom-use Claude Code plugin ships (FR-2, Recommendation A).
//
// Everything (the MCP SDK, `ws`, `zod`) is bundled in, so the output is one
// file the plugin's `.mcp.json` can launch with plain `node`. The plugin cache
// copies the plugin directory and forbids `../` references, so the bundle MUST
// be self-contained and live inside the plugin — this produces exactly that.
//
// Usage:
//   node build.mjs                 -> packages/sidecar/dist/index.js
//   node build.mjs <outfile>       -> bundle straight into a custom path
//                                     (the plugin build points this at plugin/server/index.js)
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const outfile = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(here, "dist", "index.js");

await build({
  entryPoints: [path.join(here, "src", "index.ts")],
  outfile,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  // ws ships an optional native acceleration require that esbuild would warn on;
  // it degrades gracefully to pure JS, so silence the dynamic-require noise.
  logLevel: "info",
  // Keep the bundle launchable as a plain ESM module under any Node 18+.
  banner: {
    js:
      "// LOOM sidecar — bundled, self-contained MCP server. Generated by " +
      "packages/sidecar/build.mjs; do not edit by hand.\n" +
      "import { createRequire as __loomCreateRequire } from 'node:module';\n" +
      "const require = __loomCreateRequire(import.meta.url);",
  },
});

console.log(`[loom-sidecar] bundled -> ${outfile}`);
